### ISSUE TITLE
update-database failed

### ISSUE THREAD

**Issue by oneal1801** [BrigitePeposhi/itka-inv-application#1]
Hi, 

thank you for share this amazing project.

I was trying to run the application to see how it works but when I try to run the command **"update-database"** my visual studio stop working, it fail and restart it self. I tried in 2 different computers with the same situation and it only happens with this project. It's very weird but maybe you can have any comment

thanks in advance.

**VS:** 15.9.4 and **EF:** 4.7.03062

**Comment by oneal1801** [comment]
I re-create the project in a new solution and it works ok after that, thanks anyway 👍, the only issue now is that it has performance issues when i call a method :(

**Comment by StarlinMarrero** [comment]
Bueno, klk Oneal
